# Markdownlint configuration
# Relax rules for long lines and inline HTML often used in assignments
MD013: false  # line length
MD033: false  # inline HTML
MD041: false  # first line in file should be a top-level header
